# Generated by Django 5.1.7 on 2025-06-13 18:48

import autoslug.fields
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title')),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='car/single')),
                ('small_description', models.TextField(blank=True, null=True)),
                ('overview', wagtail.fields.StreamField([('paragraph', 0), ('h4', 1), ('h5', 2), ('h6', 2), ('ordered_list', 3), ('unordered_list', 4), ('table', 5), ('blockquote_1', 6), ('url', 7), ('spacer', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['p', 'a']}), 1: ('wagtail.blocks.CharBlock', (), {'features': ['h4']}), 2: ('wagtail.blocks.CharBlock', (), {'features': ['h6']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['ol']}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul']}), 5: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Table'}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.URLBlock', (), {}), 8: ('wagtail.blocks.static_block.StaticBlock', (), {'label': 'Spacer'})}, null=True)),
                ('youtube_embed', models.TextField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('pdf_catalogue', models.FileField(blank=True, null=True, upload_to='products/pdf_catalogues')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CarSpecCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('color_hex', models.CharField(max_length=6)),
                ('image', models.ImageField(upload_to='products/color_variants')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_color_variants', to='a_dealer.car')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car/gallery')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_gallery', to='a_dealer.car')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('carspec_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_specs_category', to='a_dealer.carspeccategory')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CarSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_spec', to='a_dealer.car')),
                ('carspec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_car', to='a_dealer.specification')),
            ],
        ),
    ]
