# Generated by Django 5.1.7 on 2025-05-09 09:31

import django.db.models.deletion
import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Denza', max_length=255, verbose_name='Site Name')),
                ('company_name', models.CharField(default='Denza Indonesia', max_length=255, verbose_name='Company Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logo/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicon/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Branding Setting',
            },
        ),
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_display', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_prefix', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_floating_whatsapp', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_blog', models.BooleanField(default=True)),
                ('module_portfolio', models.BooleanField(default=False)),
                ('module_event', models.BooleanField(default=False)),
                ('module_product', models.BooleanField(default=False)),
                ('module_service', models.BooleanField(default=False)),
                ('module_booking', models.BooleanField(default=False)),
                ('module_property', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageSEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_meta_key', models.TextField(blank=True, max_length=100, null=True)),
                ('home_meta_desc', models.TextField(blank=True, max_length=160, null=True)),
                ('blog_meta_key', models.TextField(blank=True, max_length=100, null=True)),
                ('blog_meta_desc', models.TextField(blank=True, max_length=160, null=True)),
                ('product_meta_key', models.TextField(blank=True, max_length=100, null=True)),
                ('product_meta_desc', models.TextField(blank=True, max_length=160, null=True)),
                ('portfolio_meta_key', models.TextField(blank=True, max_length=100, null=True)),
                ('portfolio_meta_desc', models.TextField(blank=True, max_length=160, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('tiktok_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', wagtail_color_panel.fields.ColorField(default='#0846b4', max_length=7)),
                ('secondary_color', models.CharField(default='#2a7aff')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
