# Generated by Django 5.1.7 on 2025-05-09 09:33

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='secondary_color',
            field=wagtail_color_panel.fields.ColorField(default='#2a7aff', max_length=7),
        ),
    ]
