# Generated by Django 5.1.7 on 2025-05-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0002_alter_themesetting_secondary_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesetting',
            name='site',
        ),
    ]
