# Generated by Django 5.1.7 on 2025-05-09 09:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0003_remove_themesetting_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#0846b4', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#2a7aff', image_field=None, max_length=25, samples=None),
        ),
    ]
