# Generated by Django 5.1.7 on 2025-05-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0004_alter_themesetting_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageseosetting',
            name='booking_meta_desc',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='pageseosetting',
            name='booking_meta_key',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageseosetting',
            name='event_meta_desc',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='pageseosetting',
            name='event_meta_key',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageseosetting',
            name='property_meta_desc',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='pageseosetting',
            name='property_meta_key',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageseosetting',
            name='service_meta_desc',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='pageseosetting',
            name='service_meta_key',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
