# Generated by Django 5.1.7 on 2025-05-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0005_pageseosetting_booking_meta_desc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleFlag',
        ),
    ]
