# Generated by Django 5.1.7 on 2025-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0006_delete_moduleflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsetting',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='branding/emblem/', verbose_name='Logo'),
        ),
    ]
