# Generated by Django 5.1.7 on 2025-05-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0007_brandingsetting_emblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsetting',
            name='emblem_rounded',
            field=models.ImageField(blank=True, null=True, upload_to='branding/emblem/', verbose_name='Emblem'),
        ),
        migrations.AlterField(
            model_name='brandingsetting',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='branding/emblem/', verbose_name='Emblem'),
        ),
    ]
