# Generated by Django 5.1.7 on 2025-05-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0008_brandingsetting_emblem_rounded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsetting',
            name='emblem_rounded',
            field=models.ImageField(blank=True, null=True, upload_to='branding/emblem/', verbose_name='Emblem Ronded BG'),
        ),
    ]
