# Generated by Django 5.1.7 on 2025-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0009_alter_brandingsetting_emblem_rounded'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatusSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_soon', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
