# Generated by Django 5.1.7 on 2025-06-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0010_sitestatussetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatussetting',
            name='coming_soon',
        ),
        migrations.RemoveField(
            model_name='sitestatussetting',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='sitestatussetting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('maintenance', 'Maintenance')], default='active', max_length=20),
        ),
    ]
