# Generated by Django 5.1.7 on 2025-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_globalsetting', '0011_remove_sitestatussetting_coming_soon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSocialEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
