# Generated by Django 5.1.7 on 2025-05-12 12:23

import colorfield.fields
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkDirectory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True)),
                ('enable_social_link', models.BooleanField(default=False)),
                ('enable_floating_whatsapp', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('primary_color', colorfield.fields.ColorField(default='#0f0f0f', image_field=None, max_length=7, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#0f0f0f', image_field=None, max_length=7, samples=None)),
                ('background_color', colorfield.fields.ColorField(default='#f2f2f2', image_field=None, max_length=7, samples=None)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_desc', models.TextField(blank=True)),
                ('meta_key', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Link Directory Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('text_content', 'Text Content')], default='link', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='link_items/images')),
                ('text_content', wagtail.fields.StreamField([('paragraph', 0), ('h4', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['p', 'a']}), 1: ('wagtail.blocks.CharBlock', (), {'features': ['h4']})}, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_items', to='a_page.linkdirectory')),
            ],
            options={
                'verbose_name': 'Link Item',
            },
        ),
    ]
