# Generated by Django 5.1.7 on 2025-06-12 08:24

import autoslug.fields
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(default=None, upload_to='marketplace/logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('small_description', models.TextField(blank=True, max_length=500)),
                ('description', wagtail.fields.StreamField([('paragraph', 0), ('h4', 1), ('h5', 2), ('h6', 2), ('ordered_list', 3), ('unordered_list', 4), ('blockquote_1', 5), ('url', 6), ('button', 9), ('spacer', 10), ('html', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['p', 'a']}), 1: ('wagtail.blocks.CharBlock', (), {'features': ['h4']}), 2: ('wagtail.blocks.CharBlock', (), {'features': ['h6']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['ol']}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul']}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.URLBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.URLBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('text', 7), ('url', 8)]], {'icon': 'plus'}), 10: ('wagtail.blocks.static_block.StaticBlock', (), {'label': 'Spacer'}), 11: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code', 'label': 'Raw HTML'})}, null=True)),
                ('is_highlight', models.BooleanField(default=False)),
                ('meta_key', models.TextField(blank=True, max_length=255, null=True)),
                ('meta_desc', models.TextField(blank=True, max_length=160, null=True)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_product.productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='product/gallery')),
                ('product', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='a_product.product')),
            ],
            options={
                'verbose_name': 'Product Gallery',
                'verbose_name_plural': 'Product Galleries',
            },
        ),
        migrations.CreateModel(
            name='ProductMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_text', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_product.marketplace')),
                ('product', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_marketplace', to='a_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('product', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_spec', to='a_product.product')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_product.specification')),
            ],
        ),
    ]
