# Generated by Django 5.1.7 on 2025-05-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog/category'),
        ),
    ]
