# Generated by Django 5.1.7 on 2025-05-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0002_alter_blogcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='total_visit',
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
