# Generated by Django 5.1.7 on 2025-05-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
