# Generated by Django 5.1.7 on 2025-06-13 11:31

import autoslug.fields
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('small_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='blog/content')),
                ('content', wagtail.fields.StreamField([('paragraph', 0), ('h4', 1), ('h5', 2), ('h6', 2), ('ordered_list', 3), ('unordered_list', 4), ('table', 5), ('blockquote_1', 6), ('image_1280x720', 7), ('image_1280x1280', 8), ('image_1280x800', 9), ('url', 10), ('button', 13), ('spacer', 14), ('html', 15)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['p', 'a']}), 1: ('wagtail.blocks.CharBlock', (), {'features': ['h4']}), 2: ('wagtail.blocks.CharBlock', (), {'features': ['h6']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['ol']}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul']}), 5: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Table'}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '1280 x 720', 'label': 'Image 1280x720'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '1280 x 1280', 'label': 'Image 1280x1280'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '1280 x 800', 'label': 'Image 1280x800'}), 10: ('wagtail.blocks.URLBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'required': True}), 12: ('wagtail.blocks.URLBlock', (), {'required': True}), 13: ('wagtail.blocks.StructBlock', [[('text', 11), ('url', 12)]], {'icon': 'plus'}), 14: ('wagtail.blocks.static_block.StaticBlock', (), {'label': 'Spacer'}), 15: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code', 'label': 'Raw HTML'})}, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_category', to='a_service.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
